### ISSUE TITLE
The local_mode on chef 12.0.0.alpha.2 can't create object to local filesystem.

### ISSUE THREAD

**Issue by sawanoboly** [chef/chef-zero#99]
Which causes this problem, chef or chef-zero ?

## case `chef-client -z`

creates empty node.

```
# ./bin/chef-client -z
Starting Chef Client, version 12.0.0.alpha.2
...
Chef Client finished, 0/0 resources updated in 1.441195439 seconds

# cat nodes/mynode.json 
{
  "name": "mynode"
}
```

## Case `knife ** create --local`

The Chef-Zero returns 500.

```
# ./bin/knife role create hoge -z --disable-editing 
WARNING: No knife configuration file found
WARN: No cookbooks directory found at or above current directory.  Assuming /root/12.
ERROR: #<NoMethodError: undefined method `has_key?' for role[hoge]:Chef::Role>
/root/12/vendor/bundle/ruby/1.9.1/bundler/gems/chef-4e9b9ff85663/lib/chef/chef_fs/data_handler/data_handler_base.rb:69:in `block in normalize_hash'
/root/12/vendor/bundle/ruby/1.9.1/bundler/gems/chef-4e9b9ff85663/lib/chef/chef_fs/data_handler/data_handler_base.rb:68:in `each_pair'
/root/12/vendor/bundle/ruby/1.9.1/bundler/gems/chef-4e9b9ff85663/lib/chef/chef_fs/data_handler/data_handler_base.rb:68:in `normalize_hash'
/root/12/vendor/bundle/ruby/1.9.1/bundler/gems/chef-4e9b9ff85663/lib/chef/chef_fs/data_handler/role_data_handler.rb:9:in `normalize'
/root/12/vendor/bundle/ruby/1.9.1/bundler/gems/chef-4e9b9ff85663/lib/chef/chef_fs/file_system/chef_repository_file_system_entry.rb:68:in `minimize'
/root/12/vendor/bundle/ruby/1.9.1/bundler/gems/chef-4e9b9ff85663/lib/chef/chef_fs/file_system/chef_repository_file_system_entry.rb:61:in `write'
/root/12/vendor/bundle/ruby/1.9.1/bundler/gems/chef-4e9b9ff85663/lib/chef/chef_fs/file_system/file_system_entry.rb:56:in `create_child'
/root/12/vendor/bundle/ruby/1.9.1/bundler/gems/chef-4e9b9ff85663/lib/chef/chef_fs/file_system/multiplexed_dir.rb:44:in `create_child'
/root/12/vendor/bundle/ruby/1.9.1/bundler/gems/chef-4e9b9ff85663/lib/chef/chef_fs/chef_fs_data_store.rb:124:in `block in create'
/root/12/vendor/bundle/ruby/1.9.1/bundler/gems/chef-4e9b9ff85663/lib/chef/chef_fs/chef_fs_data_store.rb:449:in `with_dir'
/root/12/vendor/bundle/ruby/1.9.1/bundler/gems/chef-4e9b9ff85663/lib/chef/chef_fs/chef_fs_data_store.rb:122:in `create'
/root/12/vendor/bundle/ruby/1.9.1/gems/chef-zero-3.2/lib/chef_zero/data_store/v1_to_v2_adapter.rb:34:in `block in create'
/root/12/vendor/bundle/ruby/1.9.1/gems/chef-zero-3.2/lib/chef_zero/data_store/v1_to_v2_adapter.rb:113:in `fix_exceptions'
/root/12/vendor/bundle/ruby/1.9.1/gems/chef-zero-3.2/lib/chef_zero/data_store/v1_to_v2_adapter.rb:33:in `create'
/root/12/vendor/bundle/ruby/1.9.1/gems/chef-zero-3.2/lib/chef_zero/rest_base.rb:150:in `create_data'
/root/12/vendor/bundle/ruby/1.9.1/gems/chef-zero-3.2/lib/chef_zero/endpoints/rest_list_endpoint.rb:31:in `post'
/root/12/vendor/bundle/ruby/1.9.1/gems/chef-zero-3.2/lib/chef_zero/rest_base.rb:30:in `call'
/root/12/vendor/bundle/ruby/1.9.1/gems/chef-zero-3.2/lib/chef_zero/rest_router.rb:24:in `call'
/root/12/vendor/bundle/ruby/1.9.1/gems/chef-zero-3.2/lib/chef_zero/server.rb:553:in `block in app'
/root/12/vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `call'
/root/12/vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
/opt/chef/embedded/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
/opt/chef/embedded/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
/opt/chef/embedded/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
ERROR: Server returned error 500 for http://localhost:8889/roles, retrying 1/5 in 3s
```

**Comment by sawanoboly** [comment]
close by https://github.com/chef/chef/commit/e809bb40b1340309c86edac9fb5cf7f179f8f7ec
